from django.db import models

# Create your models here.
class Post(models.Model):
    substancia = models.TextField() 
    cnpj = models.CharField(max_length=20), 
    laboratorio = models.CharField(max_length=255)
    codigo_ggrem = models.CharField(max_length=40)  
    registro = models.CharField(max_length=50)
    ean_1 = models.CharField(max_length=50)
    ean_2 = models.CharField(max_length=50) 
    ean_3 = models.CharField(max_length=50) 
    produto = models.CharField(max_length=255) 
    apresentacao = models.CharField(max_length=255)
    classe_terapeutica = models.CharField(max_length=255)
    tipo_de_produto_status = models.CharField(max_length=30)
    regime_de_preco = models.CharField(max_length=30)
    pf_sem_imposto = models.DecimalField(max_digits=10, decimal_places=2)  
    pf_0 = models.DecimalField(max_digits=10, decimal_places=2) 
    pf_12 = models.DecimalField(max_digits=10, decimal_places=2)   
    pf_17 = models.DecimalField(max_digits=10, decimal_places=2)   
    pf_17_alc = models.DecimalField(max_digits=10, decimal_places=2) 
    pf_17_5 = models.DecimalField(max_digits=10, decimal_places=2) 
    pf_17_5_alc = models.DecimalField(max_digits=10, decimal_places=2) 
    pf_18 = models.DecimalField(max_digits=10, decimal_places=2) 
    pf_18_alc = models.DecimalField(max_digits=10, decimal_places=2) 
    pf_20 = models.DecimalField(max_digits=10, decimal_places=2) 
    pmc_0 = models.DecimalField(max_digits=10, decimal_places=2) 
    pmc_12 = models.DecimalField(max_digits=10, decimal_places=2) 
    pmc_17 = models.DecimalField(max_digits=10, decimal_places=2) 
    pmc_17_alc = models.DecimalField(max_digits=10, decimal_places=2) 
    pmc_17_5 = models.DecimalField(max_digits=10, decimal_places=2) 
    pmc_17_5_alc = models.DecimalField(max_digits=10, decimal_places=2) 
    pmc_18 = models.DecimalField(max_digits=10, decimal_places=2) 
    pmc_18_alc = models.DecimalField(max_digits=10, decimal_places=2) 
    pmc_20 = models.DecimalField(max_digits=10, decimal_places=2) 
    restricao_hospitalar = models.CharField(max_length=10) 
    cap = models.CharField(max_length=10) 
    confaz_87 = models.CharField(max_length=10)
    icms_0 = models.CharField(max_length=10) 
    analise_recursal = models.IntegerField, 
    lista_de_concessao_de_credito_tributario = models.CharField(max_length=10)
    comercializado_2020 = models.CharField(max_length=10), 
    tarja = models.CharField(max_length=50)
