# Generated by Django 5.1.6 on 2025-02-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substancia', models.TextField()),
                ('laboratorio', models.CharField(max_length=255)),
                ('codigo_ggrem', models.CharField(max_length=40)),
                ('registro', models.CharField(max_length=50)),
                ('ean_1', models.CharField(max_length=50)),
                ('ean_2', models.CharField(max_length=50)),
                ('ean_3', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=255)),
                ('apresentacao', models.CharField(max_length=255)),
                ('classe_terapeutica', models.CharField(max_length=255)),
                ('tipo_de_produto_status', models.CharField(max_length=30)),
                ('regime_de_preco', models.CharField(max_length=30)),
                ('pf_sem_imposto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_0', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_12', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_17', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_17_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_17_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_17_5_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_18', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_18_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmc_0', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmc_12', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmc_17', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmc_17_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmc_17_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmc_17_5_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmc_18', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmc_18_alc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmc_20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restricao_hospitalar', models.CharField(max_length=10)),
                ('cap', models.CharField(max_length=10)),
                ('confaz_87', models.CharField(max_length=10)),
                ('icms_0', models.CharField(max_length=10)),
                ('lista_de_concessao_de_credito_tributario', models.CharField(max_length=10)),
                ('tarja', models.CharField(max_length=50)),
            ],
        ),
    ]
